name: Docker images build and push

on:
  pull_request:
    branches:
      - main
      - dev
      - 'stabilization/**'
  push:
    branches:
      - main

  schedule:
    - cron: '0 4 * * 0'

jobs:
  build_image:
    if: github.event_name == 'pull_request' || github.event_name == 'schedule'
    runs-on: wisevision-runner
    container:
      image: ubuntu:22.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install Docker CLI
        run: |
          apt-get update
          apt-get install -y docker.io

      - name: Docker build
        run: |
          docker build -t mcp_server_ros_2 .

  build_and_push_image:
    if: github.event_name == 'push'
    runs-on: wisevision-runner
    container:
      image: ubuntu:22.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install Docker CLI
        run: |
          apt-get update
          apt-get install -y docker.io

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image for multiple architectures
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
          --file Dockerfile \
          --tag ${{ secrets.DOCKER_HUB_USERNAME }}/mcp_server_ros_2:humble \
          --push \
          .